### ISSUE TITLE
The birthdate function is not valid

### ISSUE THREAD

**Issue by fungiboletus** [navikt/fnrvalidator#110]
Hei,

I was looking at how you validate the D-Numbers in this library because there is a difference in the definition of D-Numbers between the law and what says Directoratet for e-helse, but it looks like your `birthdate` function uses an algorithm that is not using any of these two definitions. From a quick look it's not the end of the world but it may accepts numbers that are invalid with a birthdate in the end of February and some lap year mix-ups.

https://lovdata.no/dokument/SF/forskrift/2017-07-14-1201/KAPITTEL_2#KAPITTEL_2
https://ehelse.no/standarder/identifikatorer-for-personer (and check the PDF attachment).

**Comment by jksolbakken** [comment]
Sorry for the late reply, notifications for this repo was turned off for some reason. The birthdate function subtracts 4 from the first digit for d-numbers as per the spec. If the date is otherwise invalid it will be caught by the date and/or checksum validation. The date validation should also work with leap years. If the date is feb 29 (or bigger) in a non leap year the JavaScript Date object will roll over to March, and that will be caught by the month equality check.
